/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UslugiRouteImport } from './routes/uslugi'
import { Route as PolitikaKonfidencialnostiRouteImport } from './routes/politika-konfidencialnosti'
import { Route as OtzyvyRouteImport } from './routes/otzyvy'
import { Route as ObektyRouteImport } from './routes/obekty'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as KontaktyRouteImport } from './routes/kontakty'
import { Route as CenyRouteImport } from './routes/ceny'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UslugiIndexRouteImport } from './routes/uslugi.index'
import { Route as UslugiSlugRouteImport } from './routes/uslugi.$slug'

const UslugiRoute = UslugiRouteImport.update({
  id: '/uslugi',
  path: '/uslugi',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaKonfidencialnostiRoute =
  PolitikaKonfidencialnostiRouteImport.update({
    id: '/politika-konfidencialnosti',
    path: '/politika-konfidencialnosti',
    getParentRoute: () => rootRouteImport,
  } as any)
const OtzyvyRoute = OtzyvyRouteImport.update({
  id: '/otzyvy',
  path: '/otzyvy',
  getParentRoute: () => rootRouteImport,
} as any)
const ObektyRoute = ObektyRouteImport.update({
  id: '/obekty',
  path: '/obekty',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktyRoute = KontaktyRouteImport.update({
  id: '/kontakty',
  path: '/kontakty',
  getParentRoute: () => rootRouteImport,
} as any)
const CenyRoute = CenyRouteImport.update({
  id: '/ceny',
  path: '/ceny',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiIndexRoute = UslugiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UslugiRoute,
} as any)
const UslugiSlugRoute = UslugiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UslugiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ceny': typeof CenyRoute
  '/kontakty': typeof KontaktyRoute
  '/o-nas': typeof ONasRoute
  '/obekty': typeof ObektyRoute
  '/otzyvy': typeof OtzyvyRoute
  '/politika-konfidencialnosti': typeof PolitikaKonfidencialnostiRoute
  '/uslugi': typeof UslugiRouteWithChildren
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/uslugi/': typeof UslugiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ceny': typeof CenyRoute
  '/kontakty': typeof KontaktyRoute
  '/o-nas': typeof ONasRoute
  '/obekty': typeof ObektyRoute
  '/otzyvy': typeof OtzyvyRoute
  '/politika-konfidencialnosti': typeof PolitikaKonfidencialnostiRoute
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/uslugi': typeof UslugiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ceny': typeof CenyRoute
  '/kontakty': typeof KontaktyRoute
  '/o-nas': typeof ONasRoute
  '/obekty': typeof ObektyRoute
  '/otzyvy': typeof OtzyvyRoute
  '/politika-konfidencialnosti': typeof PolitikaKonfidencialnostiRoute
  '/uslugi': typeof UslugiRouteWithChildren
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/uslugi/': typeof UslugiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ceny'
    | '/kontakty'
    | '/o-nas'
    | '/obekty'
    | '/otzyvy'
    | '/politika-konfidencialnosti'
    | '/uslugi'
    | '/uslugi/$slug'
    | '/uslugi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ceny'
    | '/kontakty'
    | '/o-nas'
    | '/obekty'
    | '/otzyvy'
    | '/politika-konfidencialnosti'
    | '/uslugi/$slug'
    | '/uslugi'
  id:
    | '__root__'
    | '/'
    | '/ceny'
    | '/kontakty'
    | '/o-nas'
    | '/obekty'
    | '/otzyvy'
    | '/politika-konfidencialnosti'
    | '/uslugi'
    | '/uslugi/$slug'
    | '/uslugi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CenyRoute: typeof CenyRoute
  KontaktyRoute: typeof KontaktyRoute
  ONasRoute: typeof ONasRoute
  ObektyRoute: typeof ObektyRoute
  OtzyvyRoute: typeof OtzyvyRoute
  PolitikaKonfidencialnostiRoute: typeof PolitikaKonfidencialnostiRoute
  UslugiRoute: typeof UslugiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uslugi': {
      id: '/uslugi'
      path: '/uslugi'
      fullPath: '/uslugi'
      preLoaderRoute: typeof UslugiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika-konfidencialnosti': {
      id: '/politika-konfidencialnosti'
      path: '/politika-konfidencialnosti'
      fullPath: '/politika-konfidencialnosti'
      preLoaderRoute: typeof PolitikaKonfidencialnostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otzyvy': {
      id: '/otzyvy'
      path: '/otzyvy'
      fullPath: '/otzyvy'
      preLoaderRoute: typeof OtzyvyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obekty': {
      id: '/obekty'
      path: '/obekty'
      fullPath: '/obekty'
      preLoaderRoute: typeof ObektyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakty': {
      id: '/kontakty'
      path: '/kontakty'
      fullPath: '/kontakty'
      preLoaderRoute: typeof KontaktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceny': {
      id: '/ceny'
      path: '/ceny'
      fullPath: '/ceny'
      preLoaderRoute: typeof CenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/': {
      id: '/uslugi/'
      path: '/'
      fullPath: '/uslugi/'
      preLoaderRoute: typeof UslugiIndexRouteImport
      parentRoute: typeof UslugiRoute
    }
    '/uslugi/$slug': {
      id: '/uslugi/$slug'
      path: '/$slug'
      fullPath: '/uslugi/$slug'
      preLoaderRoute: typeof UslugiSlugRouteImport
      parentRoute: typeof UslugiRoute
    }
  }
}

interface UslugiRouteChildren {
  UslugiSlugRoute: typeof UslugiSlugRoute
  UslugiIndexRoute: typeof UslugiIndexRoute
}

const UslugiRouteChildren: UslugiRouteChildren = {
  UslugiSlugRoute: UslugiSlugRoute,
  UslugiIndexRoute: UslugiIndexRoute,
}

const UslugiRouteWithChildren =
  UslugiRoute._addFileChildren(UslugiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CenyRoute: CenyRoute,
  KontaktyRoute: KontaktyRoute,
  ONasRoute: ONasRoute,
  ObektyRoute: ObektyRoute,
  OtzyvyRoute: OtzyvyRoute,
  PolitikaKonfidencialnostiRoute: PolitikaKonfidencialnostiRoute,
  UslugiRoute: UslugiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
