/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// It should not be edited manually.
// It WAS generated by running `npx @tanstack/router-vite-plugin generate` and may be edited.

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as TsenyImport } from './routes/tseny'
import { Route as ServicesImport } from './routes/services'
import { Route as PortfolioImport } from './routes/portfolio'
import { Route as GorodaImport } from './routes/goroda'
import { Route as BlogImport } from './routes/blog'
import { Route as AboutImport } from './routes/about'
import { Route as ContactsImport } from './routes/contacts'
import { Route as PrivacyPolicyImport } from './routes/privacy-policy'
import { Route as CookiePolicyImport } from './routes/cookie-policy'
import { Route as AdminSettingsImport } from './routes/admin.settings'
import { Route as AdminServicesImport } from './routes/admin.services'
import { Route as AdminReviewsImport } from './routes/admin.reviews'
import { Route as AdminProjectsImport } from './routes/admin.projects'
import { Route as AdminPostsImport } from './routes/admin.posts'
import { Route as AdminLeadsImport } from './routes/admin.leads'
import { Route as AdminGalleryImport } from './routes/admin.gallery'
import { Route as AdminPricesImport } from './routes/admin.prices'
import { Route as ServicesSlugImport } from './routes/services.$slug'
import { Route as PortfolioSlugImport } from './routes/portfolio.$slug'
import { Route as GorodaCityImport } from './routes/goroda.$city'
import { Route as BlogSlugImport } from './routes/blog.$slug'

const AuthRoute = AuthImport.update({ path: '/auth', getParentRoute: () => rootRoute } as any)
const AdminRoute = AdminImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRoute } as any)
const IndexRoute = IndexImport.update({ path: '/', getParentRoute: () => rootRoute } as any)
const TsenyRoute = TsenyImport.update({ path: '/tseny', getParentRoute: () => rootRoute } as any)
const ServicesRoute = ServicesImport.update({ path: '/services', getParentRoute: () => rootRoute } as any)
const PortfolioRoute = PortfolioImport.update({ path: '/portfolio', getParentRoute: () => rootRoute } as any)
const GorodaRoute = GorodaImport.update({ path: '/goroda', getParentRoute: () => rootRoute } as any)
const BlogRoute = BlogImport.update({ path: '/blog', getParentRoute: () => rootRoute } as any)
const AboutRoute = AboutImport.update({ path: '/about', getParentRoute: () => rootRoute } as any)
const ContactsRoute = ContactsImport.update({ path: '/contacts', getParentRoute: () => rootRoute } as any)
const PrivacyPolicyRoute = PrivacyPolicyImport.update({ path: '/privacy-policy', getParentRoute: () => rootRoute } as any)
const CookiePolicyRoute = CookiePolicyImport.update({ path: '/cookie-policy', getParentRoute: () => rootRoute } as any)
const AdminSettingsRoute = AdminSettingsImport.update({ path: '/settings', getParentRoute: () => AdminRoute } as any)
const AdminServicesRoute = AdminServicesImport.update({ path: '/services', getParentRoute: () => AdminRoute } as any)
const AdminReviewsRoute = AdminReviewsImport.update({ path: '/reviews', getParentRoute: () => AdminRoute } as any)
const AdminProjectsRoute = AdminProjectsImport.update({ path: '/projects', getParentRoute: () => AdminRoute } as any)
const AdminPostsRoute = AdminPostsImport.update({ path: '/posts', getParentRoute: () => AdminRoute } as any)
const AdminLeadsRoute = AdminLeadsImport.update({ path: '/leads', getParentRoute: () => AdminRoute } as any)
const AdminGalleryRoute = AdminGalleryImport.update({ path: '/gallery', getParentRoute: () => AdminRoute } as any)
const AdminPricesRoute = AdminPricesImport.update({ path: '/prices', getParentRoute: () => AdminRoute } as any)
const ServicesSlugRoute = ServicesSlugImport.update({ path: '/$slug', getParentRoute: () => ServicesRoute } as any)
const PortfolioSlugRoute = PortfolioSlugImport.update({ path: '/$slug', getParentRoute: () => PortfolioRoute } as any)
const GorodaCityRoute = GorodaCityImport.update({ path: '/$city', getParentRoute: () => GorodaRoute } as any)
const BlogSlugRoute = BlogSlugImport.update({ path: '/$slug', getParentRoute: () => BlogRoute } as any)

export interface FileRoutesByPath {
  '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute; }
  '/about': { id: '/about'; path: '/about'; fullPath: '/about'; preLoaderRoute: typeof AboutImport; parentRoute: typeof rootRoute; }
  '/blog': { id: '/blog'; path: '/blog'; fullPath: '/blog'; preLoaderRoute: typeof BlogImport; parentRoute: typeof rootRoute; }
  '/contacts': { id: '/contacts'; path: '/contacts'; fullPath: '/contacts'; preLoaderRoute: typeof ContactsImport; parentRoute: typeof rootRoute; }
  '/cookie-policy': { id: '/cookie-policy'; path: '/cookie-policy'; fullPath: '/cookie-policy'; preLoaderRoute: typeof CookiePolicyImport; parentRoute: typeof rootRoute; }
  '/goroda': { id: '/goroda'; path: '/goroda'; fullPath: '/goroda'; preLoaderRoute: typeof GorodaImport; parentRoute: typeof rootRoute; }
  '/goroda/$city': { id: '/goroda/$city'; path: '/$city'; fullPath: '/goroda/$city'; preLoaderRoute: typeof GorodaCityImport; parentRoute: typeof GorodaRoute; }
  '/portfolio': { id: '/portfolio'; path: '/portfolio'; fullPath: '/portfolio'; preLoaderRoute: typeof PortfolioImport; parentRoute: typeof rootRoute; }
  '/portfolio/$slug': { id: '/portfolio/$slug'; path: '/$slug'; fullPath: '/portfolio/$slug'; preLoaderRoute: typeof PortfolioSlugImport; parentRoute: typeof PortfolioRoute; }
  '/privacy-policy': { id: '/privacy-policy'; path: '/privacy-policy'; fullPath: '/privacy-policy'; preLoaderRoute: typeof PrivacyPolicyImport; parentRoute: typeof rootRoute; }
  '/services': { id: '/services'; path: '/services'; fullPath: '/services'; preLoaderRoute: typeof ServicesImport; parentRoute: typeof rootRoute; }
  '/services/$slug': { id: '/services/$slug'; path: '/$slug'; fullPath: '/services/$slug'; preLoaderRoute: typeof ServicesSlugImport; parentRoute: typeof ServicesRoute; }
  '/tseny': { id: '/tseny'; path: '/tseny'; fullPath: '/tseny'; preLoaderRoute: typeof TsenyImport; parentRoute: typeof rootRoute; }
  '/blog/$slug': { id: '/blog/$slug'; path: '/$slug'; fullPath: '/blog/$slug'; preLoaderRoute: typeof BlogSlugImport; parentRoute: typeof BlogRoute; }
  '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthImport; parentRoute: typeof rootRoute; }
  '/admin': { id: '/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AdminImport; parentRoute: typeof rootRoute; }
  '/admin/gallery': { id: '/admin/gallery'; path: '/gallery'; fullPath: '/admin/gallery'; preLoaderRoute: typeof AdminGalleryImport; parentRoute: typeof AdminRoute; }
  '/admin/prices': { id: '/admin/prices'; path: '/prices'; fullPath: '/admin/prices'; preLoaderRoute: typeof AdminPricesImport; parentRoute: typeof AdminRoute; }
  '/admin/leads': { id: '/admin/leads'; path: '/leads'; fullPath: '/admin/leads'; preLoaderRoute: typeof AdminLeadsImport; parentRoute: typeof AdminRoute; }
  '/admin/posts': { id: '/admin/posts'; path: '/posts'; fullPath: '/admin/posts'; preLoaderRoute: typeof AdminPostsImport; parentRoute: typeof AdminRoute; }
  '/admin/projects': { id: '/admin/projects'; path: '/projects'; fullPath: '/admin/projects'; preLoaderRoute: typeof AdminProjectsImport; parentRoute: typeof AdminRoute; }
  '/admin/reviews': { id: '/admin/reviews'; path: '/reviews'; fullPath: '/admin/reviews'; preLoaderRoute: typeof AdminReviewsImport; parentRoute: typeof AdminRoute; }
  '/admin/services': { id: '/admin/services'; path: '/services'; fullPath: '/admin/services'; preLoaderRoute: typeof AdminServicesImport; parentRoute: typeof AdminRoute; }
  '/admin/settings': { id: '/admin/settings'; path: '/settings'; fullPath: '/admin/settings'; preLoaderRoute: typeof AdminSettingsImport; parentRoute: typeof AdminRoute; }
}

export function createRouteTree() {
  const routeTree = rootRoute._addFileChildren([
    IndexRoute,
    AboutRoute,
    BlogRoute._addFileChildren([BlogSlugRoute]),
    ContactsRoute,
    CookiePolicyRoute,
    GorodaRoute._addFileChildren([GorodaCityRoute]),
    PortfolioRoute._addFileChildren([PortfolioSlugRoute]),
    PrivacyPolicyRoute,
    ServicesRoute._addFileChildren([ServicesSlugRoute]),
    TsenyRoute,
    AuthRoute,
    AdminRoute._addFileChildren([
      AdminLeadsRoute,
      AdminGalleryRoute,
      AdminPricesRoute,
      AdminPostsRoute,
      AdminProjectsRoute,
      AdminReviewsRoute,
      AdminServicesRoute,
      AdminSettingsRoute,
    ]),
  ])
  return routeTree
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath extends FileRoutesByPath {}
}
